### PR TITLE
Add concert service gazebo

### PR DESCRIPTION
**Pull request by piyushk**
Added a concert service to use multiple robots in gazebo. This PR adds all the robot-independent code, and provides an abstract base class that needs to be implemented in a robot-specific manner to use this code.

### CODE REVIEW

**Comment by stonier** [comment]
@piyushk , is this ready to go?

Also, could you add a README to get it running with a reference robot/service (e.g. the segbots) so that we can test it at anytime. I'll also get @bit-pirate to take it for a road test before committing.

**Comment by piyushk** [comment]
This PR is ready to go, but the segbot specific module needs a bit of work. I'll add the README and work on the last remaining changes and get back in a few hours.

**Comment by stonier** [comment]
:+1:

**Comment by piyushk** [comment]
I've fixed all remaining issues with the demo. The two segway robots roam around in gazebo. The README should help run the demo.

**Comment by piyushk** [comment]
The PR is ready to go.

**Comment by bit-pirate** [comment]
Looking into this now.

**Comment by bit-pirate** [comment]
This is awesome! I believe this will help us a lot in the future! Great job, @piyushk !

Here are the few things I noticed:
- Missing dependency for `gnome-konsole`. Had to install it to get the concert working. (related with #4)
- Robots stop moving after reaching the second corner.
- https://github.com/utexas-bwi/segbot_rocon/issues
- More documentation for how to prepare and start this service and what it does (maybe just put the contents of the readme in a tutorial/package page on the ROS wiki)

**Comment by stonier** [comment]
I don't think we can add dependencies for the terminal it launches - like `rocon_launch`, it works by sniffing to see what type of terminal you have got with the assumption that you _have_ a terminal.

On precise if you are running kubuntu default it sees you have konsole and then falls back to gnome (should have info messages popping up for this). If you have another terminal as default, then the approach would be to hook in further terminal support into rocon_launch.

**Comment by piyushk** [comment]
I'll tend to the last remaining issues tomorrow. With updated code from both repos, robots continue to move indefinitely for me. This was an issue with one of my configurations (the bug is unrelated to the concert framework). Can you confirm that this still happens for you?

**Comment by bit-pirate** [comment]
> Can you confirm that this still happens for you?

Yes, it still does even with the lasted code.

The left robot reaches the second corner, while the right one gets stuck at the first corner already.

Left robot log:

```
[INFO] [WallTime: 1398337491.204730] [16.968000] Rapp Manager : Gazebo Concertb32c71fb790d46e6977e92d34a8ce2d0
[ WARN] [1398337491.296486070, 17.014000000]: Waiting on transform from guimul/base_footprint to map to become available before running costmap, tf error: 
[ INFO] [1398337491.446175787, 17.112000000]: Loading from pre-hydro parameter style
[ INFO] [1398337491.480886788, 17.130000000]: Using plugin "static_layer"
[ INFO] [1398337491.552930679, 17.158000000]: Requesting the map...
[ INFO] [1398337491.704760063, 17.258000000]: Resizing costmap to 500 X 500 at 0.050000 m/pix
[INFO] [WallTime: 1398337491.739290] [0.000000] SegbotStroll: Resolved robot frame: guimul/base_footprint
[ INFO] [1398337491.866511759, 17.360000000]: Received a 500 X 500 map at 0.050000 m/pix
[ INFO] [1398337491.870437064, 17.360000000]: Using plugin "obstacle_layer"
[ INFO] [1398337491.872419224, 17.360000000]:     Subscribed to Topics: scan kinect_scan
[ INFO] [1398337491.916795978, 17.387000000]: Using plugin "inflation_layer"
[ INFO] [1398337492.081524803, 17.488000000]: Loading from pre-hydro parameter style
[ INFO] [1398337492.108813153, 17.505000000]: Using plugin "obstacle_layer"
[ INFO] [1398337492.167496427, 17.530000000]:     Subscribed to Topics: scan kinect_scan
[ INFO] [1398337492.202331338, 17.551000000]: Using plugin "inflation_layer"
[ INFO] [1398337492.315960253, 17.611000000]: Created local_planner eband_local_planner/EBandPlannerROS
[ INFO] [1398337493.240316312, 18.247000000]: Global plan set to elastic band for optimization
[ INFO] [1398337508.813324312, 28.897000000]: TrajectoryController: Goal reached with distance 0.01, -0.03 (od = 0.18); sending zero velocity
[ INFO] [1398337508.972072934, 29.008000000]: Global plan set to elastic band for optimization
```

Right robot log:

```
[INFO] [WallTime: 1398337489.189564] [16.063000] Rapp Manager : Gazebo Concertb32c71fb790d46e6977e92d34a8ce2d0
[ WARN] [1398337489.333261765, 16.148000000]: Waiting on transform from kobuki/base_footprint to map to become available before running costmap, tf error: 
[ INFO] [1398337489.473315442, 16.240000000]: Loading from pre-hydro parameter style
[ INFO] [1398337489.514263847, 16.249000000]: Using plugin "static_layer"
[ INFO] [1398337489.601955591, 16.271000000]: Requesting the map...
[INFO] [WallTime: 1398337489.689326] [0.000000] SegbotStroll: Resolved robot frame: kobuki/base_footprint
[ INFO] [1398337489.878234438, 16.372000000]: Resizing costmap to 500 X 500 at 0.050000 m/pix
[ INFO] [1398337490.104102837, 16.472000000]: Received a 500 X 500 map at 0.050000 m/pix
[ INFO] [1398337490.109087150, 16.473000000]: Using plugin "obstacle_layer"
[ INFO] [1398337490.112535861, 16.474000000]:     Subscribed to Topics: scan kinect_scan
[ INFO] [1398337490.151287063, 16.487000000]: Using plugin "inflation_layer"
[ INFO] [1398337490.308023397, 16.538000000]: Loading from pre-hydro parameter style
[ INFO] [1398337490.332094768, 16.546000000]: Using plugin "obstacle_layer"
[ INFO] [1398337490.385100568, 16.566000000]:     Subscribed to Topics: scan kinect_scan
[ INFO] [1398337490.426849848, 16.581000000]: Using plugin "inflation_layer"
[ INFO] [1398337490.520686138, 16.612000000]: Created local_planner eband_local_planner/EBandPlannerROS
[ INFO] [1398337491.278157002, 17.001000000]: Global plan set to elastic band for optimization
```

**Comment by piyushk** [comment]
Alright, I think I figured out the robot not moving issue:
1. I never released an updated version of eband_local_planner after fixing a few problems: https://github.com/utexas-bwi/eband_local_planner/issues/12
2. All the friction/inertia values for the segway robots are made up, and were tested on a surface with fairly low friction to ensure that the robots produced reasonable behavior. The default friction for empty.world is too high, and different from what I use for all my worlds. I've created a custom empty world for this demo with a low friction coefficient.
3. I've switched the plugin to `gazebo_ros_planar_move` from `gazebo_ros_diff_drive`. While this makes the simulation less realistic, in practice it works extremely well.

@bit-pirate: Can you download eband_local_planner from source, update all the code and re-test? We'll release eband in the meantime.

**Comment by bit-pirate** [comment]
Justed tested this with the updated code and the deb install of the eband planner (since it seems identlical with the source) and it works well.

So, from my side +1 for merging. @stonier will do the merge.

**Comment by piyushk** [comment]
You're probably pulling in debs from shadow-fixed. The latest version of eband (0.2.1) hasn't reached the public repository yet.

**Comment by bit-pirate** [comment]
> You're probably pulling in debs from shadow-fixed.

That's correct. I'm running 0.2.1.

**Comment by stonier** [comment]
@piushk do you think we should include `officially supported` robot manager classes (e.g. segbot, turtlebot) in this package?

**Comment by piyushk** [comment]
I thought about that, and I think robot maintainers should maintain independent packages. I've already run into the case where the auto-generated roslaunch script for the robot, as well as the rocon_launch script need to be different for every application. As long as we have enough tutorials with a segbot/turtlebot, we should be fine. We'll also need to include instructions on tf namespacing/prefixing which the robot maintainers will have to follow to get this to work correctly.

Let me get our scenario up and running (sometime in the next day or two) and revisit this issue.

**Comment by stonier** [comment]
Ok.

**Comment by piyushk** [comment]
I've added some additional documentation on the ROS wiki: http://wiki.ros.org/concert_service_gazebo

**Comment by piyushk** [comment]
I've also finished documenting the two example concerts that use this code: 
http://wiki.ros.org/segbot_gazebo_concert
http://wiki.ros.org/bwi_guidance_concert (This is our research scenario).

**Pull request merged**
